package EloRatingSystem.Models.Achievement;

public enum AchievementType {
    RATING_REACHED,
    RATING_REACHED_SOLO,
    TOTAL_WINS,
    TOTAL_WINS_SOLO,
    WIN_STREAK,
    WIN_STREAK_SOLO,
    TOTAL_WINS_10_ZERO,
    TOTAL_WINS_10_ZERO_SOLO,
    WIN_10_ZERO_AS_DEFENDER,
    WIN_10_ZERO_AS_ATTACKER,
    WIN_10_ZERO_SOLO,
    TOTAL_MONTHLY_2V2_WINS,
    WIN_AGAINST_HIGHER_RATED,
    WIN_AGAINST_HIGHER_RATED_SOLO

}
